/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.calcular_nomina.vista;

import com.calcular_nomina.controlador.ControladorNomina;
import com.calcular_nomina.controlador.ControladorUsuario;
import com.calcular_nomina.excepciones.UsuarioExcepcion;
import com.calcular_nomina.modelo.Empleado;
import com.calcular_nomina.modelo.Operario;
import com.calcular_nomina.modelo.Supervisor;
import com.calcular_nomina.modelo.Usuario;
import com.calcular_nomina.modelo.Vigilante;
import java.awt.TrayIcon;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carloaiza
 */
public class MDINomina extends javax.swing.JFrame {

    private ControladorUsuario controlUsuarios;
    private Usuario usuarioAutenticado;
    private ControladorNomina controlNomina;
    
    /**
     * Creates new form MDINomina
     */
    public MDINomina() {
        initComponents();//CRea todas las instancia
        controlarEstadoMenus();
        controlUsuarios = new ControladorUsuario();  
        controlNomina = new ControladorNomina();
        txtCorreo.setText("carloaiza@umanizales.edu.co");
        txtContrasenia.setText("123456");
        llenarEmpleados();
        cmbTipoEmpleado.setSelectedIndex(0);
        evaluarComboTipoEmpleado();
    }
    
    private void evaluarComboTipoEmpleado()
    {
        //Posición del combo seleccionada
        switch(cmbTipoEmpleado.getSelectedIndex())
        {
            case 0:
            case 2:
                lblHorasTrabajadas.setVisible(false);
                spnHorasTrabajadas.setVisible(false);
                spnHorasTrabajadas.setValue(0); 
                lblSalario.setVisible(true);
                txtSalario.setVisible(true);
                break;
            case 1:
                lblHorasTrabajadas.setVisible(true);
                spnHorasTrabajadas.setVisible(true);
                spnHorasTrabajadas.setValue(0);                
                lblSalario.setVisible(false);
                txtSalario.setVisible(false);
                break;
        }
        
    }
    
    
    private void llenarEmpleados()
    {
        ///Extrae el modelo de la tabla (Columnas y filas)
        DefaultTableModel model = (DefaultTableModel) tblEmpleados.getModel();
        //Limpia toda la tabla
        model.getDataVector().removeAllElements();
        //Declara un arreglo de objetos para representar una fila de la tabla
        //Object[] fila = {"75147235","Carlos Loaiza",2000000,false};
        //Adiciona la fila a la tabla
        //model.addRow(fila);
        //Refresca la tabla
        
        //Recorriendo el controlador de empleados y llenando mi tabla
        for(Empleado emp: controlNomina.getEmpleados())
        {
            if(emp!=null)
            {
                Object[] fila = {emp.getCedula(),emp.getNombre(),
                emp.getSalario(),emp.isLicencia(), emp.getClass().getSimpleName()};
                model.addRow(fila);
            }
        }
        
        tblEmpleados.repaint();
        
    }
    
    
    public void controlarEstadoMenus()
    {       
        // Si ya se presentó una autenticación
        mnuListarEmpleados.setEnabled(false);
        mnuCrearEmpleado.setEnabled(false);
        mnuCalcularNomina.setEnabled(false);
        
        mnuCalcularNomina.setVisible(false);
        mnuListarEmpleados.setVisible(false);
        mnuCrearEmpleado.setVisible(false);
        
        if(usuarioAutenticado!=null)
        {
            //Evaluar el rol
            switch(usuarioAutenticado.getRol().getCodigo())
            {
                case 1:
                    mnuListarEmpleados.setEnabled(true);
                    mnuCrearEmpleado.setEnabled(true);
                    mnuCalcularNomina.setEnabled(true);
                    
                    mnuListarEmpleados.setVisible(true);
                    mnuCrearEmpleado.setVisible(true);
                    mnuCalcularNomina.setVisible(true);
                    break;
                case 2:
                    mnuListarEmpleados.setEnabled(true);
                    mnuListarEmpleados.setVisible(true);
                    break;
            }
        }
        
        
         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jifLogin = new javax.swing.JInternalFrame();
        lblUsuario = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jifListarEmpleados = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jifRegistrarEmpleado = new javax.swing.JInternalFrame();
        btnRegistrar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblSalario = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        chkLicencia = new javax.swing.JCheckBox();
        lblTipoEmpleado = new javax.swing.JLabel();
        cmbTipoEmpleado = new javax.swing.JComboBox<>();
        lblHorasTrabajadas = new javax.swing.JLabel();
        spnHorasTrabajadas = new javax.swing.JSpinner();
        menuBar = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuListarEmpleados = new javax.swing.JMenuItem();
        mnuCrearEmpleado = new javax.swing.JMenuItem();
        mnuCalcularNomina = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifLogin.setIconifiable(true);
        jifLogin.setMaximizable(true);
        jifLogin.setTitle("Ingreso a Cálculo Nómina");
        jifLogin.setVisible(true);

        lblUsuario.setText("* Correo:");

        lblContrasenia.setText("* Contrasenia");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifLoginLayout = new javax.swing.GroupLayout(jifLogin.getContentPane());
        jifLogin.getContentPane().setLayout(jifLoginLayout);
        jifLoginLayout.setHorizontalGroup(
            jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifLoginLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(btnIngresar)
                .addGap(130, 130, 130))
            .addGroup(jifLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContrasenia)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(txtContrasenia))
                .addContainerGap())
        );
        jifLoginLayout.setVerticalGroup(
            jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifLoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasenia)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIngresar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        desktopPane.add(jifLogin);
        jifLogin.setBounds(50, 80, 370, 220);

        jifListarEmpleados.setClosable(true);
        jifListarEmpleados.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifListarEmpleados.setIconifiable(true);
        jifListarEmpleados.setMaximizable(true);
        jifListarEmpleados.setResizable(true);
        jifListarEmpleados.setTitle("Listado de Empleados");
        jifListarEmpleados.setPreferredSize(new java.awt.Dimension(1024, 900));
        jifListarEmpleados.setVisible(false);

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Nombre", "Salario", "Licencia", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        javax.swing.GroupLayout jifListarEmpleadosLayout = new javax.swing.GroupLayout(jifListarEmpleados.getContentPane());
        jifListarEmpleados.getContentPane().setLayout(jifListarEmpleadosLayout);
        jifListarEmpleadosLayout.setHorizontalGroup(
            jifListarEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifListarEmpleadosLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(489, Short.MAX_VALUE))
        );
        jifListarEmpleadosLayout.setVerticalGroup(
            jifListarEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifListarEmpleadosLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(499, Short.MAX_VALUE))
        );

        desktopPane.add(jifListarEmpleados);
        jifListarEmpleados.setBounds(100, 30, 800, 900);

        jifRegistrarEmpleado.setClosable(true);
        jifRegistrarEmpleado.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifRegistrarEmpleado.setIconifiable(true);
        jifRegistrarEmpleado.setMaximizable(true);
        jifRegistrarEmpleado.setResizable(true);
        jifRegistrarEmpleado.setTitle("Registrar Empleado");
        jifRegistrarEmpleado.setToolTipText("");
        jifRegistrarEmpleado.setVisible(false);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre:");

        lblCedula.setText("Cédula:");

        lblSalario.setText("Salario:");

        chkLicencia.setText("Licencia?");

        lblTipoEmpleado.setText("Tipo de Empleado:");

        cmbTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vigilante", "Operario", "Supervisor" }));
        cmbTipoEmpleado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoEmpleadoItemStateChanged(evt);
            }
        });
        cmbTipoEmpleado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbTipoEmpleadoPropertyChange(evt);
            }
        });

        lblHorasTrabajadas.setText("Horas Trabajadas:");

        javax.swing.GroupLayout jifRegistrarEmpleadoLayout = new javax.swing.GroupLayout(jifRegistrarEmpleado.getContentPane());
        jifRegistrarEmpleado.getContentPane().setLayout(jifRegistrarEmpleadoLayout);
        jifRegistrarEmpleadoLayout.setHorizontalGroup(
            jifRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifRegistrarEmpleadoLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jifRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifRegistrarEmpleadoLayout.createSequentialGroup()
                        .addGroup(jifRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSalario)
                            .addComponent(lblCedula)
                            .addComponent(lblNombre)
                            .addComponent(lblTipoEmpleado)
                            .addComponent(lblHorasTrabajadas))
                        .addGap(18, 18, 18)
                        .addGroup(jifRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jifRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chkLicencia)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(txtCedula)
                                .addComponent(txtSalario)
                                .addComponent(cmbTipoEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(spnHorasTrabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifRegistrarEmpleadoLayout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addGap(205, 205, 205))))
        );
        jifRegistrarEmpleadoLayout.setVerticalGroup(
            jifRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifRegistrarEmpleadoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jifRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(24, 24, 24)
                .addGroup(jifRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalario)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoEmpleado)
                    .addComponent(cmbTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorasTrabajadas)
                    .addComponent(spnHorasTrabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkLicencia)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        desktopPane.add(jifRegistrarEmpleado);
        jifRegistrarEmpleado.setBounds(180, 20, 440, 440);

        mnuArchivo.setMnemonic('f');
        mnuArchivo.setText("Inicio");

        mnuListarEmpleados.setBackground(new java.awt.Color(104, 130, 157));
        mnuListarEmpleados.setMnemonic('o');
        mnuListarEmpleados.setText("Listar Empleados");
        mnuListarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarEmpleadosActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuListarEmpleados);

        mnuCrearEmpleado.setMnemonic('s');
        mnuCrearEmpleado.setText("Crear Empleado");
        mnuCrearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearEmpleadoActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuCrearEmpleado);

        mnuCalcularNomina.setMnemonic('a');
        mnuCalcularNomina.setText("CalcularNomina");
        mnuArchivo.add(mnuCalcularNomina);

        mnuSalir.setMnemonic('x');
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        menuBar.add(mnuArchivo);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        
        JOptionPane.showMessageDialog(rootPane, "Gracias por utilizar mi app. Vuelve pronto");
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try {            
            usuarioAutenticado= controlUsuarios.verificarUsuario(txtCorreo.getText(), txtContrasenia.getText());
            ///Es porque todo está bien
            controlarEstadoMenus();
            jifLogin.hide();             
            JOptionPane.showMessageDialog(rootPane,"Bienvenido "
                    +usuarioAutenticado.getNombre(),"Ingreso Exitoso",1);
            
        } catch (UsuarioExcepcion ex) {
            JOptionPane.showMessageDialog(rootPane,ex.getMessage(), "Error",0);
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void mnuListarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarEmpleadosActionPerformed
        // TODO add your handling code here:
        if(jifListarEmpleados.isIcon())
        {
            try {
                jifListarEmpleados.setIcon(false);
            } catch (PropertyVetoException ex) {
                System.out.println("No se pudo restaurar el formulario listar empleados");
            }
        }
        
        jifListarEmpleados.show();
        
    }//GEN-LAST:event_mnuListarEmpleadosActionPerformed

    private void mnuCrearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearEmpleadoActionPerformed
        // TODO add your handling code here:
        if(jifRegistrarEmpleado.isIcon())
        {
            try {
                jifRegistrarEmpleado.setIcon(Boolean.FALSE);
            } catch (PropertyVetoException ex) {
                System.out.println("NO se encontraba minimizado");
            }
        }
        jifRegistrarEmpleado.show();
        
    }//GEN-LAST:event_mnuCrearEmpleadoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
       ///IMplementar las excepciones de negocio
       //Campos obligatorios
       // Salario positivo , capturar si ingresan letras en el salario
       //Tipo de empleado
       
       Empleado empleadoAdicionar=null;
       
       switch(cmbTipoEmpleado.getSelectedIndex())
       {
           case 0:
               empleadoAdicionar=
                       new Vigilante(txtCedula.getText(), 
                               txtNombre.getText(), 
                               Double.parseDouble(txtSalario.getText()), 
                               chkLicencia.isSelected());
               break;
           case 1:
               int horasT=Integer.parseInt(
                       spnHorasTrabajadas.getValue().toString());
               empleadoAdicionar=
                       new Operario(horasT,
                               txtCedula.getText(), 
                               txtNombre.getText(),                               
                               chkLicencia.isSelected());
               break;
           case 2:
               empleadoAdicionar= new Supervisor(txtCedula.getText(), 
                               txtNombre.getText(), 
                               Double.parseDouble(txtSalario.getText()), 
                               chkLicencia.isSelected());
       }        
        
       String mensaje= controlNomina.adicionarEmpleado(empleadoAdicionar);
       llenarEmpleados();
       JOptionPane.showMessageDialog(rootPane, mensaje);
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cmbTipoEmpleadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbTipoEmpleadoPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbTipoEmpleadoPropertyChange

    private void cmbTipoEmpleadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoEmpleadoItemStateChanged
        // TODO add your handling code here:
        evaluarComboTipoEmpleado();
    }//GEN-LAST:event_cmbTipoEmpleadoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDINomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDINomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDINomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDINomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDINomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox chkLicencia;
    private javax.swing.JComboBox<String> cmbTipoEmpleado;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JInternalFrame jifListarEmpleados;
    private javax.swing.JInternalFrame jifLogin;
    private javax.swing.JInternalFrame jifRegistrarEmpleado;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblHorasTrabajadas;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTipoEmpleado;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuCalcularNomina;
    private javax.swing.JMenuItem mnuCrearEmpleado;
    private javax.swing.JMenuItem mnuListarEmpleados;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JSpinner spnHorasTrabajadas;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables

}
